export * from './endsWith';
export * from './includes';
export * from './longerThan';
export * from './ofLength';
export * from './ofMaximumLength';
export * from './ofMinimumLength';
export * from './shorterThan';
export * from './startsWith';
export * from './usingRegEx';
